version: "3"

services:
  postgres:
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 5s
      retries: 5
    image: postgres:13.3
    environment:
      POSTGRES_PASSWORD: infin
    restart: on-failure
    volumes:
      - db:/var/lib/postgresql/data
  backend:
    build: .
    depends_on:
      postgres:
        condition: service_healthy
    restart: on-failure
    ports:
      - 80:80
  parser:
    build:
      context: .
      dockerfile: Dockerfile.parser
    depends_on:
      postgres:
        condition: service_healthy

volumes:
  db:
